# The FIRI-2018 model data is originally provided by M. Friedrich, C. Pock, and K. Torkar.
# It is available at: https://figshare.com/s/357cb03b3e5bed649bbc under the CC BY 4.0 license (https://creativecommons.org/licenses/by/4.0/#).
# I have repackaged the data for compatibility with Julia Artifacts and made it available at figshare.com under the same CC BY 4.0 license.

[firi]
git-tree-sha1 = "90cc57fddd53cb427ea3b91dd4bd85037d42b494"

    [[firi.download]]
    sha256 = "8b443d97e2f575c53f2b51e34495fa0b4edb3ca0cd53b681bbe5a0fa44b15025"
    url = "https://ndownloader.figshare.com/files/26640602?private_link=33a146841a3f74a74590"
